#!/usr/bin/env bash
# display the record type and the adress where it points to, for a given domain and subdomain

domain=$1
subdomain=$2

check_subdomain() {
    result=$(dig $1.$domain | grep "IN" | head -n 1)
    record=$(echo $result | awk '{print $4}')
    destination=$(echo $result | awk '{print $5}')

    echo "The subdomain $1 is a $record record and points to $destination"
}

if [ -z "$subdomain" ]
then
    for sub in www lb-01 web-01 web-02
    do
        check_subdomain $sub
    done
else
    check_subdomain $subdomain
fi
